/* Generated By:JavaCC: Do not edit this line. EtiqParserConstants.java */
package EtiquetaParser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface EtiqParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int identificador = 1;
  /** RegularExpression Id. */
  int cualquiera = 2;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<identificador>",
    "<cualquiera>",
  };

}
