//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XForms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XForms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ICON1 {
            get {
                object obj = ResourceManager.GetObject("ICON1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ICON11 {
            get {
                object obj = ResourceManager.GetObject("ICON11", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon if_document_open_118911 {
            get {
                object obj = ResourceManager.GetObject("if_document_open_118911", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon if_document_open_1189111 {
            get {
                object obj = ResourceManager.GetObject("if_document_open_1189111", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon if_Error_381599 {
            get {
                object obj = ResourceManager.GetObject("if_Error_381599", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon if_Report_669954 {
            get {
                object obj = ResourceManager.GetObject("if_Report_669954", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap if_shield_error_299056 {
            get {
                object obj = ResourceManager.GetObject("if_shield_error_299056", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon if_Warning_34248 {
            get {
                object obj = ResourceManager.GetObject("if_Warning_34248", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;doc&gt;
        ///    &lt;brackets left=&quot;&lt;&quot; right=&quot;&gt;&quot; /&gt;
        ///    &lt;style name=&quot;Maroon&quot; color=&quot;Maroon&quot; fontStyle=&quot;Bold,Italic&quot; /&gt;
        ///    &lt;style name=&quot;Blue&quot; color=&quot;Blue&quot;/&gt;
        ///    &lt;style name=&quot;Red&quot; color=&quot;Red&quot; backColor=&quot;#f5f5e5&quot; /&gt;
        ///    &lt;rule style=&quot;Blue&quot;&gt;&lt;|/&gt;|&lt;/|&gt;&lt;/rule&gt;
        ///    &lt;rule style=&quot;Maroon&quot;&gt;&lt;(?&lt;range&gt;[!\w\d]+)&lt;/rule&gt;
        ///    &lt;rule style=&quot;Maroon&quot;&gt;&lt;/(?&lt;range&gt;[\w\d]+)&gt;&lt;/rule&gt;
        ///    &lt;rule style=&quot;Red&quot; options=&quot;Multiline&quot;&gt;(?&lt;range&gt;\S+?)=&apos;[^&apos;]*
        ///        &apos;|(?&lt;range&gt;\S+)=&quot;[^&quot;]*&quot;|(?&lt;range&gt;\S+)=\S+&lt;/rule&gt;
        ///    &lt;folding start=&quot;&lt;div&quot; finish [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xform {
            get {
                return ResourceManager.GetString("xform", resourceCulture);
            }
        }
    }
}
