/* Generated By:JavaCC: Do not edit this line. MultimediaParserConstants.java */
package MParser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MultimediaParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int media_im = 6;
  /** RegularExpression Id. */
  int media_vid = 7;
  /** RegularExpression Id. */
  int media_aud = 8;
  /** RegularExpression Id. */
  int reproduccion = 9;
  /** RegularExpression Id. */
  int mas = 10;
  /** RegularExpression Id. */
  int menos = 11;
  /** RegularExpression Id. */
  int por = 12;
  /** RegularExpression Id. */
  int div = 13;
  /** RegularExpression Id. */
  int mod = 14;
  /** RegularExpression Id. */
  int pot = 15;
  /** RegularExpression Id. */
  int igual = 16;
  /** RegularExpression Id. */
  int diferente = 17;
  /** RegularExpression Id. */
  int mayor = 18;
  /** RegularExpression Id. */
  int menor = 19;
  /** RegularExpression Id. */
  int mayorigual = 20;
  /** RegularExpression Id. */
  int menorigual = 21;
  /** RegularExpression Id. */
  int and = 22;
  /** RegularExpression Id. */
  int not = 23;
  /** RegularExpression Id. */
  int or = 24;
  /** RegularExpression Id. */
  int punto = 25;
  /** RegularExpression Id. */
  int dpunto = 26;
  /** RegularExpression Id. */
  int arroba = 27;
  /** RegularExpression Id. */
  int oPar = 28;
  /** RegularExpression Id. */
  int cPar = 29;
  /** RegularExpression Id. */
  int cad_min = 30;
  /** RegularExpression Id. */
  int cad_fila = 31;
  /** RegularExpression Id. */
  int cad_max = 32;
  /** RegularExpression Id. */
  int finalizar = 33;
  /** RegularExpression Id. */
  int iniciar = 34;
  /** RegularExpression Id. */
  int sino = 35;
  /** RegularExpression Id. */
  int vf = 36;
  /** RegularExpression Id. */
  int opcion = 37;
  /** RegularExpression Id. */
  int coma = 38;
  /** RegularExpression Id. */
  int f_cadena = 39;
  /** RegularExpression Id. */
  int f_subcad = 40;
  /** RegularExpression Id. */
  int f_poscad = 41;
  /** RegularExpression Id. */
  int f_booleano = 42;
  /** RegularExpression Id. */
  int f_entero = 43;
  /** RegularExpression Id. */
  int f_tam = 44;
  /** RegularExpression Id. */
  int f_pow = 45;
  /** RegularExpression Id. */
  int f_log = 46;
  /** RegularExpression Id. */
  int f_log10 = 47;
  /** RegularExpression Id. */
  int f_abs = 48;
  /** RegularExpression Id. */
  int f_sin = 49;
  /** RegularExpression Id. */
  int f_cos = 50;
  /** RegularExpression Id. */
  int f_tan = 51;
  /** RegularExpression Id. */
  int f_sqrt = 52;
  /** RegularExpression Id. */
  int f_pi = 53;
  /** RegularExpression Id. */
  int f_fecha = 54;
  /** RegularExpression Id. */
  int f_hora = 55;
  /** RegularExpression Id. */
  int f_fechahora = 56;
  /** RegularExpression Id. */
  int f_random = 57;
  /** RegularExpression Id. */
  int f_min = 58;
  /** RegularExpression Id. */
  int f_max = 59;
  /** RegularExpression Id. */
  int f_hoy = 60;
  /** RegularExpression Id. */
  int f_ahora = 61;
  /** RegularExpression Id. */
  int identificador = 62;
  /** RegularExpression Id. */
  int entero = 63;
  /** RegularExpression Id. */
  int decimal = 64;
  /** RegularExpression Id. */
  int str1 = 65;
  /** RegularExpression Id. */
  int str2 = 66;
  /** RegularExpression Id. */
  int verdadero = 67;
  /** RegularExpression Id. */
  int falso = 68;
  /** RegularExpression Id. */
  int fecha = 69;
  /** RegularExpression Id. */
  int hora = 70;
  /** RegularExpression Id. */
  int fechahora = 71;
  /** RegularExpression Id. */
  int err = 72;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\t\"",
    "\"media_imagen\"",
    "\"media_video\"",
    "\"media_audio\"",
    "\"reproduccion\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"div\"",
    "\"mod\"",
    "\"^\"",
    "\"=\"",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"&&\"",
    "\"!\"",
    "\"||\"",
    "\".\"",
    "\"..\"",
    "\"@\"",
    "\"(\"",
    "\")\"",
    "\"cad_min\"",
    "\"cad_fila\"",
    "\"cad_max\"",
    "\"finalizar\"",
    "\"iniciar\"",
    "\"si_no\"",
    "\"v_f\"",
    "\"opcion\"",
    "\",\"",
    "\"cadena\"",
    "\"subcad\"",
    "\"poscad\"",
    "\"booleano\"",
    "\"entero\"",
    "\"tam\"",
    "\"pow\"",
    "\"log\"",
    "\"log10\"",
    "\"abs\"",
    "\"sin\"",
    "\"cos\"",
    "\"tan\"",
    "\"sqrt\"",
    "\"pi\"",
    "\"fecha\"",
    "\"hora\"",
    "\"fechahora\"",
    "\"random\"",
    "\"min\"",
    "\"max\"",
    "\"hoy\"",
    "\"ahora\"",
    "<identificador>",
    "<entero>",
    "<decimal>",
    "<str1>",
    "<str2>",
    "\"verdadero\"",
    "\"falso\"",
    "<fecha>",
    "<hora>",
    "<fechahora>",
    "<err>",
  };

}
