/* Generated By:JavaCC: Do not edit this line. XLSParserConstants.java */
package Analizadores;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface XLSParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int oKey = 1;
  /** RegularExpression Id. */
  int cKey = 2;
  /** RegularExpression Id. */
  int ptComa = 3;
  /** RegularExpression Id. */
  int nll = 4;
  /** RegularExpression Id. */
  int dPts = 5;
  /** RegularExpression Id. */
  int oBrack = 6;
  /** RegularExpression Id. */
  int cBrack = 7;
  /** RegularExpression Id. */
  int coma = 8;
  /** RegularExpression Id. */
  int titulo_form = 9;
  /** RegularExpression Id. */
  int idform = 10;
  /** RegularExpression Id. */
  int estilo = 11;
  /** RegularExpression Id. */
  int importa = 12;
  /** RegularExpression Id. */
  int codigo_gl = 13;
  /** RegularExpression Id. */
  int codigo_pr = 14;
  /** RegularExpression Id. */
  int conf = 15;
  /** RegularExpression Id. */
  int pag = 16;
  /** RegularExpression Id. */
  int tod = 17;
  /** RegularExpression Id. */
  int cuadricu = 18;
  /** RegularExpression Id. */
  int opcions = 19;
  /** RegularExpression Id. */
  int pregu = 20;
  /** RegularExpression Id. */
  int encus = 21;
  /** RegularExpression Id. */
  int tipo = 22;
  /** RegularExpression Id. */
  int idpregu = 23;
  /** RegularExpression Id. */
  int etiqueta = 24;
  /** RegularExpression Id. */
  int sugerir = 25;
  /** RegularExpression Id. */
  int requerido = 26;
  /** RegularExpression Id. */
  int requeridomsn = 27;
  /** RegularExpression Id. */
  int pordefecto = 28;
  /** RegularExpression Id. */
  int lectura = 29;
  /** RegularExpression Id. */
  int calculo = 30;
  /** RegularExpression Id. */
  int multimedia = 31;
  /** RegularExpression Id. */
  int restringir = 32;
  /** RegularExpression Id. */
  int restringirmsn = 33;
  /** RegularExpression Id. */
  int codigo_pre = 34;
  /** RegularExpression Id. */
  int codigo_post = 35;
  /** RegularExpression Id. */
  int aplicable = 36;
  /** RegularExpression Id. */
  int apariencia = 37;
  /** RegularExpression Id. */
  int parametro = 38;
  /** RegularExpression Id. */
  int verdadero = 39;
  /** RegularExpression Id. */
  int repeticion = 40;
  /** RegularExpression Id. */
  int falso = 41;
  /** RegularExpression Id. */
  int uno = 42;
  /** RegularExpression Id. */
  int cero = 43;
  /** RegularExpression Id. */
  int unop = 44;
  /** RegularExpression Id. */
  int cerop = 45;
  /** RegularExpression Id. */
  int texto = 46;
  /** RegularExpression Id. */
  int entero = 47;
  /** RegularExpression Id. */
  int decimal = 48;
  /** RegularExpression Id. */
  int rango = 49;
  /** RegularExpression Id. */
  int condicion = 50;
  /** RegularExpression Id. */
  int fecha = 51;
  /** RegularExpression Id. */
  int hora = 52;
  /** RegularExpression Id. */
  int fechahora = 53;
  /** RegularExpression Id. */
  int sel_un = 54;
  /** RegularExpression Id. */
  int sel_mul = 55;
  /** RegularExpression Id. */
  int nota = 56;
  /** RegularExpression Id. */
  int fichero = 57;
  /** RegularExpression Id. */
  int calcular = 58;
  /** RegularExpression Id. */
  int grupo = 59;
  /** RegularExpression Id. */
  int fin = 60;
  /** RegularExpression Id. */
  int ciclo = 61;
  /** RegularExpression Id. */
  int pos = 62;
  /** RegularExpression Id. */
  int identificador = 68;
  /** RegularExpression Id. */
  int str = 69;
  /** RegularExpression Id. */
  int err = 70;
  /** RegularExpression Id. */
  int inicio = 71;
  /** RegularExpression Id. */
  int cual2 = 72;
  /** RegularExpression Id. */
  int texto_pl = 73;
  /** RegularExpression Id. */
  int otroInic = 74;
  /** RegularExpression Id. */
  int cual = 75;
  /** RegularExpression Id. */
  int texto_ex = 76;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int S2 = 1;
  /** Lexical state. */
  int S3 = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"NULL\"",
    "\":\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\"titulo_formulario\"",
    "\"idform\"",
    "\"estilo\"",
    "\"import\"",
    "\"codigo_global\"",
    "\"codigo_principal\"",
    "\"_config\"",
    "\"pagina\"",
    "\"todo\"",
    "\"cuadricula\"",
    "\"_opciones\"",
    "\"_pregunta\"",
    "\"_Encuesta\"",
    "\"tipo\"",
    "\"idpregunta\"",
    "\"etiqueta\"",
    "\"sugerir\"",
    "\"requerido\"",
    "\"requeridomsn\"",
    "\"predeterminado\"",
    "\"lectura\"",
    "\"calculo\"",
    "\"multimedia\"",
    "\"restringir\"",
    "\"restringirmsn\"",
    "\"codigo_pre\"",
    "\"codigo_post\"",
    "\"aplicable\"",
    "\"apariencia\"",
    "\"parametro\"",
    "\"verdadero\"",
    "\"repeticion\"",
    "\"falso\"",
    "\"1\"",
    "\"0\"",
    "\"0.0\"",
    "\"1.0\"",
    "\"texto\"",
    "\"entero\"",
    "\"decimal\"",
    "\"rango\"",
    "\"condicion\"",
    "\"fecha\"",
    "\"hora\"",
    "\"fechahora\"",
    "\"selecciona_uno\"",
    "\"selecciona_multiples\"",
    "\"nota\"",
    "\"fichero\"",
    "\"calcular\"",
    "\"_grupo\"",
    "\"_fin\"",
    "\"_ciclo\"",
    "<pos>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\t\"",
    "<identificador>",
    "<str>",
    "<err>",
    "\"<<\"",
    "<cual2>",
    "\">>\"",
    "\"%%\"",
    "<cual>",
    "\"%%\"",
  };

}
