/* Generated By:JavaCC: Do not edit this line. XLSParserConstants.java */
package Analizadores;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface XLSParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int oKey = 1;
  /** RegularExpression Id. */
  int cKey = 2;
  /** RegularExpression Id. */
  int ptComa = 3;
  /** RegularExpression Id. */
  int nll = 4;
  /** RegularExpression Id. */
  int dPts = 5;
  /** RegularExpression Id. */
  int titulo_form = 6;
  /** RegularExpression Id. */
  int idform = 7;
  /** RegularExpression Id. */
  int estilo = 8;
  /** RegularExpression Id. */
  int importa = 9;
  /** RegularExpression Id. */
  int codigo_gl = 10;
  /** RegularExpression Id. */
  int codigo_pr = 11;
  /** RegularExpression Id. */
  int conf = 12;
  /** RegularExpression Id. */
  int pag = 13;
  /** RegularExpression Id. */
  int tod = 14;
  /** RegularExpression Id. */
  int cuadricu = 15;
  /** RegularExpression Id. */
  int identificador = 21;
  /** RegularExpression Id. */
  int texto_pl = 22;
  /** RegularExpression Id. */
  int err = 23;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"NULL\"",
    "\":\"",
    "\"titulo_formulario\"",
    "\"idform\"",
    "\"estilo\"",
    "\"import\"",
    "\"codigo_global\"",
    "\"codigo_principal\"",
    "\"_config\"",
    "\"pagina\"",
    "\"todo\"",
    "\"cuadricula\"",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\t\"",
    "<identificador>",
    "<texto_pl>",
    "<err>",
  };

}
