/* Generated By:JavaCC: Do not edit this line. XLSParser.java */
package Analizadores;
import ASTTree.ASTNode;
import ManejoError.TError;
import java.util.ArrayList;
import Abstract.*;
import Tablas.*;

public class XLSParser implements XLSParserConstants {
    int id;
    final int PUNTOCOMA = 3;
    String imgError = "";

        //LISTA DE ERRORES
        ArrayList<TError> errores;
        TablaSimbolos simbolos;

    String extractText(String text)
    {
        text = text.replace("<<", "");
        text = text.replace(">>", "");
        return text;
    }

        public ArrayList<TError> getErrores()
        {
                return this.errores;
        }

  void skip_error_recovery(int kind, String archivo, String columna) throws ParseException {
    //ParseException e = generateParseException();  // generate the exception object.
        String ti = "Lexico";
        String m = "Caracter desconocido: ";
        Token to = getToken(1);
        if(to.kind != 27)
        {
                ti = "Sintactico";
                m = "No se esperaba: ";
                to = getToken(0);
        }
    //System.out.println("Caracter No admitido en "+archivo+", Columna: "+columna+" : "+to.image);  // print the error message
        errores.add(new TError(ti,m+to.image,columna,archivo));
    Token t;
    do {
        t = getNextToken();
    } while (t.kind != kind);
  }

//SYNTAXIS DEL LENGUAJE

// INICIO ::= CONFIG OPCIONES ENCUESTA
  final public ASTNode INICIO() throws ParseException {
    //AQUI VAN A IR LOS HIJOS DE ESTE METODO
    id = 0;
    ASTNode padre = new ASTNode(id, 0, 0, "INICIO");
    id++;
    ASTNode confi;
        ASTNode ops;
        ASTNode enc;
        errores = new ArrayList();
    //LLAMADA A LOS DEMAS
        confi = CONFIG();
    ops = OPCIONES();
    enc = ENCUESTA();
        //AQUI VA A IR EL RETORNO DEL PADRE
        padre.addHijo(confi);
                padre.addHijo(ops);
                padre.addHijo(enc);
        {if (true) return padre;}
    throw new Error("Missing return statement in function");
  }

  final public void EMPTY() throws ParseException {
                System.out.println("VACIO");
  }

//-----------------------------------------------------------------------------------------------|
//---------------------- COFIG Y SUS PRDOUCCIONES------------------------------------------------|
//-----------------------------------------------------------------------------------------------|
  final public ASTNode CONFIG() throws ParseException {
    //AQUI VAN A IR LOS HIJOS DE ESTE METODO
        id++;
    ASTNode padre = new ASTNode(id, 0, 0, "CONFIG");

    ASTNode titulof, idf, stl, imp, cglo, cpr;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case conf:
      jj_consume_token(conf);
      jj_consume_token(oKey);
      //{
      
          titulof = TITULO();
      padre.addHijo(titulof);
      idf = IDFORM();
      padre.addHijo(idf);
      stl = ESTILO();
      padre.addHijo(stl);
      imp = IMPOR();
      padre.addHijo(imp);
      cglo = CGLOBAL();
      padre.addHijo(cglo);
      cpr = CPRIN();
      padre.addHijo(cpr);
      jj_consume_token(cKey);
        {if (true) return padre;}
      break;
    default:
      jj_la1[0] = jj_gen;
      EMPTY();
                {if (true) return padre;}
    }
    throw new Error("Missing return statement in function");
  }

  final public ASTNode TITULO() throws ParseException {
    id++;
    ASTNode padre = new ASTNode(id, 0, 0, "TITULO");

    ASTNode tit;
    try {
      jj_consume_token(titulo_form);
      jj_consume_token(dPts);
      tit = TF("Configuraciones","titulo_formulario");
      jj_consume_token(ptComa);
            padre.addHijo(tit);
            {if (true) return padre;}
    } catch (ParseException e) {
        //LLAMADA AL TOKEN DE RECUPERACION
        skip_error_recovery(PUNTOCOMA, "Configuraciones", "titulo_formulario");//hasta que encuentre el punto y coma
        {if (true) return padre;}
    }
    throw new Error("Missing return statement in function");
  }

  final public ASTNode TF(String hoja, String columna) throws ParseException {
    Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case texto_pl:
      try {
        t = jj_consume_token(texto_pl);
            id++;
            {if (true) return new ASTNode(id,0,0,extractText(t.image));}
      } catch (ParseException e) {
        skip_error_recovery(PUNTOCOMA, "Configuraciones", columna);//HASTA QUE ENCUENTRE EL PUNTO Y COMA
        id++;
        {if (true) return new ASTNode(id, 0,0,"_ERR");}
      }
      break;
    case nll:
      try {
        t = jj_consume_token(nll);
            id++;
            {if (true) return new ASTNode(id,0,0,t.image);}
      } catch (ParseException e) {
        skip_error_recovery(PUNTOCOMA, "Configuraciones", columna);//HASTA QUE ENCUENTRE EL PUNTO Y COMA
        id++;
        {if (true) return new ASTNode(id, 0,0,"_ERR");}
      }
      break;
    default:
      jj_la1[1] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public ASTNode IDFORM() throws ParseException {
    id++;
    ASTNode padre = new ASTNode(id, 0, 0, "IDFORM");

    ASTNode idf;
    try {
      jj_consume_token(idform);
      jj_consume_token(dPts);
      idf = IDF();
      jj_consume_token(ptComa);
            padre.addHijo(idf);
            {if (true) return padre;}
    } catch (ParseException e) {
        //LLAMADA AL TOKEN DE RECUPERACION
        skip_error_recovery(PUNTOCOMA, "Configuraciones", "idformulario_");//hasta que encuentre el punto y coma
        {if (true) return padre;}
    }
    throw new Error("Missing return statement in function");
  }

  final public ASTNode IDF() throws ParseException {
    Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case identificador:
      try {
        t = jj_consume_token(identificador);
            id++;
            {if (true) return new ASTNode(id,0,0,t.image);}
      } catch (ParseException e) {
        skip_error_recovery(PUNTOCOMA, "Configuraciones", "idform");//HASTA QUE ENCUENTRE EL PUNTO Y COMA
        id++;
        {if (true) return new ASTNode(id, 0,0,"_ERR");}
      }
      break;
    case nll:
      try {
        t = jj_consume_token(nll);
            id++;
            {if (true) return new ASTNode(id,0,0,t.image);}
      } catch (ParseException e) {
        skip_error_recovery(PUNTOCOMA, "Configuraciones", "idform");//HASTA QUE ENCUENTRE EL PUNTO Y COMA
        id++;
        {if (true) return new ASTNode(id, 0,0,"_ERR");}
      }
      break;
    default:
      jj_la1[2] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public ASTNode ESTILO() throws ParseException {
        id++;
        ASTNode padre = new ASTNode(id, 0,0, "ESTILO");
        ASTNode est;
    try {
      jj_consume_token(estilo);
      jj_consume_token(dPts);
      est = EST();
      jj_consume_token(ptComa);
                        padre.addHijo(est);
                        {if (true) return padre;}
    } catch (ParseException e) {
                skip_error_recovery(PUNTOCOMA, "Configuraciones", "estilo");
                {if (true) return padre;}
    }
    throw new Error("Missing return statement in function");
  }

  final public ASTNode EST() throws ParseException {
        Token t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case tod:
      try {
        t = jj_consume_token(tod);
                        id++;
                        {if (true) return new ASTNode(id, 0,0, t.image);}
      } catch (ParseException e) {
                skip_error_recovery(PUNTOCOMA, "Configuraciones", "estilo");//HASTA QUE ENCUENTRE EL PUNTO Y COMA
                id++;
                {if (true) return new ASTNode(id, 0,0,"_ERR");}
      }
      break;
    case pag:
      try {
        t = jj_consume_token(pag);
                        id++;
                        {if (true) return new ASTNode(id, 0,0, t.image);}
      } catch (ParseException e) {
                skip_error_recovery(PUNTOCOMA, "Configuraciones", "estilo");//HASTA QUE ENCUENTRE EL PUNTO Y COMA
                id++;
                {if (true) return new ASTNode(id, 0,0,"_ERR");}
      }
      break;
    case cuadricu:
      try {
        t = jj_consume_token(cuadricu);
                        id++;
                        {if (true) return new ASTNode(id, 0,0, t.image);}
      } catch (ParseException e) {
                skip_error_recovery(PUNTOCOMA, "Configuraciones", "estilo");//HASTA QUE ENCUENTRE EL PUNTO Y COMA
                id++;
                {if (true) return new ASTNode(id, 0,0,"_ERR");}
      }
      break;
    default:
      jj_la1[3] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public ASTNode IMPOR() throws ParseException {
        id++;
        ASTNode padre = new ASTNode(id, 0,0, "IMPORTA");
        Token t;
    try {
      jj_consume_token(importa);
      jj_consume_token(dPts);
      t = jj_consume_token(texto_pl);
      jj_consume_token(ptComa);
                        id++;
                        padre.addHijo(new ASTNode(id,0,0, extractText(t.image)));
                        {if (true) return padre;}
    } catch (ParseException e) {
                skip_error_recovery(PUNTOCOMA, "Configuraciones", "importar");//hasta que encuentre el punto y coma
        {if (true) return padre;}
    }
    throw new Error("Missing return statement in function");
  }

  final public ASTNode CGLOBAL() throws ParseException {
        id++;
        ASTNode padre = new ASTNode(id, 0,0, "GLOBAL");
        ASTNode temp;
    try {
      jj_consume_token(codigo_gl);
      jj_consume_token(dPts);
      temp = TF("Configuraciones","codigo_global");
      jj_consume_token(ptComa);
                        padre.addHijo(temp);
                        {if (true) return padre;}
    } catch (ParseException e) {
                skip_error_recovery(PUNTOCOMA, "Configuraciones", "codigo_global");//hasta que encuentre el punto y coma
        {if (true) return padre;}
    }
    throw new Error("Missing return statement in function");
  }

  final public ASTNode CPRIN() throws ParseException {
        id++;
        ASTNode padre = new ASTNode(id, 0,0, "PRINCIPAL");
        ASTNode temp;
    try {
      jj_consume_token(codigo_pr);
      jj_consume_token(dPts);
      temp = TF("Configuraciones","codigo_principal");
      jj_consume_token(ptComa);
                        padre.addHijo(temp);
                        {if (true) return padre;}
    } catch (ParseException e) {
                skip_error_recovery(PUNTOCOMA, "Configuraciones", "codigo_principal");//hasta que encuentre el punto y coma
        {if (true) return padre;}
    }
    throw new Error("Missing return statement in function");
  }

//-----------------------------------------------------------------------------------------------|
//---------------------- OPCIONES Y SUS PRDOUCCIONES---------------------------------------------|
//-----------------------------------------------------------------------------------------------|
  final public ASTNode OPCIONES() throws ParseException {
        id++;
        ASTNode padre = new ASTNode(id,0,0,"OPCIONES");
        ASTNode lopcs;
    try {
      jj_consume_token(opcions);
      jj_consume_token(oKey);
      //{
                      lopcs = L_OPCS();
                        padre.addHijo(lopcs);
      jj_consume_token(cKey);
                        {if (true) return padre;}
    } catch (ParseException e) {
                {if (true) return padre;}
    }
    throw new Error("Missing return statement in function");
  }

  final public ASTNode L_OPCS() throws ParseException {
        id++;
        ASTNode padre = new ASTNode(id,0,0,"L_OPCS");
        ASTNode opcs;
        ASTNode l_opcs;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case nll:
    case identificador:
      opcs = OPCS();
         padre.addHijo(opcs);
      l_opcs = L_OPCS();
                padre.addHijo(l_opcs);
                {if (true) return padre;}
      break;
    default:
      jj_la1[4] = jj_gen;
      EMPTY();
                {if (true) return padre;}
    }
    throw new Error("Missing return statement in function");
  }

  final public ASTNode OPCS() throws ParseException {
        id++;
        ASTNode padre = new ASTNode(id,0,0,"OPCS");
        Token t;
        ASTNode l_entrada;
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case identificador:
        t = jj_consume_token(identificador);
        jj_consume_token(oKey);
        l_entrada = L_ENT();
        jj_consume_token(cKey);
        jj_consume_token(ptComa);
                        id++;
                        padre.addHijo(new ASTNode(id,0,0,t.image));
                        padre.addHijo(l_entrada);
                        {if (true) return padre;}
        break;
      case nll:
        jj_consume_token(nll);
                        //AQUI MENCIONAR EL ERROR DE LISTA
                        skip_error_recovery(PUNTOCOMA, "Opciones", "nombre_lista");
                        errores.add(new TError("Sintactico","Nombre de listado Invalido: NULL | Se esperaba un Id", "nombre_lista", "Opciones"));
                        {if (true) return padre;}
        break;
      default:
        jj_la1[5] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (ParseException e) {
                skip_error_recovery(PUNTOCOMA, "Opciones", "nombre_lista");//hasta que encuentre el punto y coma
                {if (true) return padre;}
    }
    throw new Error("Missing return statement in function");
  }

  final public ASTNode L_ENT() throws ParseException {
        id++;
        ASTNode padre = new ASTNode(id,0,0,"L_ENT");
        ASTNode ent;
        ASTNode l_ent;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case oBrack:
      ent = ENT();
      l_ent = L_ENT();
                padre.addHijo(ent);
                padre.addHijo(l_ent);
                {if (true) return padre;}
      break;
    default:
      jj_la1[6] = jj_gen;
      EMPTY();
         {if (true) return padre;}
    }
    throw new Error("Missing return statement in function");
  }

  final public ASTNode ENT() throws ParseException {
        id++;
        ASTNode padre = new ASTNode(id,0,0,"ENT");
        Token iden;
        Token cad;
        ASTNode mult;
    try {
      jj_consume_token(oBrack);
      iden = jj_consume_token(identificador);
      jj_consume_token(coma);
      cad = jj_consume_token(texto_pl);
      jj_consume_token(coma);
      mult = TF("Opciones","multimedia");
      jj_consume_token(cBrack);
                        id++;
                        padre.addHijo(new ASTNode(id,0,0,iden.image));
                        id++;
                        padre.addHijo(new ASTNode(id,0,0,extractText(cad.image)));
                        padre.addHijo(mult);
                        {if (true) return padre;}
    } catch (ParseException e) {
                skip_error_recovery(PUNTOCOMA, "Opciones", "nombre");//hasta que encuentre el punto y coma
                {if (true) return padre;}
    }
    throw new Error("Missing return statement in function");
  }

//-----------------------------------------------------------------------------------------------|
//---------------------- ENCUESTA Y SUS PRDOUCCIONES---------------------------------------------|
//-----------------------------------------------------------------------------------------------|
  final public ASTNode ENCUESTA() throws ParseException {
        id++;
        ASTNode padre = new ASTNode(id,0,0,"ENCUESTA");
        simbolos = new TablaSimbolos();
        Formulario f = new Formulario();
    jj_consume_token(encus);
    jj_consume_token(oKey);
    f = ENCUESTAP(f);
    jj_consume_token(cKey);
                padre.setForm(f);
                this.simbolos.printCountElements();
                {if (true) return padre;}
    throw new Error("Missing return statement in function");
  }

  final public Formulario ENCUESTAP(Formulario f) throws ParseException {
        Pregunta p;
        Grupo g;
        Ciclo c;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case pregu:
      p = PREGUNTA();
      f = ENCUESTAP(f);
                if(p!=null)
                {
                        f.addPregunta(p);
                }
                {if (true) return f;}
      break;
    default:
      jj_la1[7] = jj_gen;
      EMPTY();
                {if (true) return f;}
    }
    throw new Error("Missing return statement in function");
  }

  final public Pregunta PREGUNTA() throws ParseException {
        int ti;
        Token iden;
        Token cad;
    try {
      jj_consume_token(pregu);
      jj_consume_token(oKey);
      jj_consume_token(tipo);
      jj_consume_token(dPts);
      ti = TIPO();
      jj_consume_token(ptComa);
      jj_consume_token(idpregu);
      jj_consume_token(dPts);
      iden = jj_consume_token(identificador);
      jj_consume_token(ptComa);
      jj_consume_token(etiqueta);
      jj_consume_token(dPts);
      cad = jj_consume_token(texto_pl);
      jj_consume_token(ptComa);
      jj_consume_token(cKey);
                        Pregunta p = new Pregunta(iden.image, extractText(cad.image), ti);
                        if(simbolos.insertaEnTabla(iden.image, new Simbolo(iden.image, "Pregunta", p)))
                        {
                                {if (true) return p;}
                        }
                        this.errores.add(new TError("Semantico", "Existe ya un Simbolo con este identificador: "+iden.image,"idpregunta", "Encuesta"));
                        {if (true) return null;}
    } catch (ParseException e) {
                skip_error_recovery(PUNTOCOMA, "Encuesta", "idpregunta, etiqueta");
                {if (true) return null;}
    }
    throw new Error("Missing return statement in function");
  }

  final public int TIPO() throws ParseException {
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case texto:
        jj_consume_token(texto);
                  {if (true) return TipoPregunta.TEXTO;}
        break;
      case entero:
        jj_consume_token(entero);
                 {if (true) return TipoPregunta.ENTERO;}
        break;
      case decimal:
        jj_consume_token(decimal);
                 {if (true) return TipoPregunta.DECIMAL;}
        break;
      case rango:
        jj_consume_token(rango);
                 {if (true) return TipoPregunta.RANGO;}
        break;
      case condicion:
        jj_consume_token(condicion);
                 {if (true) return TipoPregunta.CONDICION;}
        break;
      case fecha:
        jj_consume_token(fecha);
                 {if (true) return TipoPregunta.FECHA;}
        break;
      case hora:
        jj_consume_token(hora);
                 {if (true) return TipoPregunta.HORA;}
        break;
      case fechahora:
        jj_consume_token(fechahora);
                 {if (true) return TipoPregunta.FECHAHORA;}
        break;
      case sel_un:
        jj_consume_token(sel_un);
                 {if (true) return TipoPregunta.SELEC_UNO;}
        break;
      case sel_mul:
        jj_consume_token(sel_mul);
                 {if (true) return TipoPregunta.SELEC_MULT;}
        break;
      case nota:
        jj_consume_token(nota);
                 {if (true) return TipoPregunta.NOTA;}
        break;
      case fichero:
        jj_consume_token(fichero);
                 {if (true) return TipoPregunta.FICHERO;}
        break;
      case calcular:
        jj_consume_token(calcular);
                 {if (true) return TipoPregunta.CALCULAR;}
        break;
      default:
        jj_la1[8] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (ParseException e) {
                skip_error_recovery(PUNTOCOMA,"Encuesta", "Tipo");
                {if (true) return 14;}
    }
    throw new Error("Missing return statement in function");
  }

  /** Generated Token Manager. */
  public XLSParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[9];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x8000,0x10,0x10,0x70000,0x10,0x10,0x40,0x100000,0x0,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x0,0x40000000,0x20000000,0x0,0x20000000,0x20000000,0x0,0x0,0xfff800,};
   }

  /** Constructor with InputStream. */
  public XLSParser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public XLSParser(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new XLSParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 9; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 9; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public XLSParser(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new XLSParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 9; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 9; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public XLSParser(XLSParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 9; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(XLSParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 9; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[64];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 9; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 64; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
