/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.event.KeyEvent;

/**
 *
 * @author ricar
 */
public class EditorTexto extends javax.swing.JPanel {

    /**
     * Creates new form EditorTexto
     */
    public EditorTexto() {
        initComponents();
    }
    
    public EditorTexto(String cadena)
    {
        initComponents();
        this.Texto.setText(cadena);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Texto = new javax.swing.JTextArea();

        Texto.setColumns(20);
        Texto.setFont(new java.awt.Font("Consolas", 0, 13)); // NOI18N
        Texto.setLineWrap(true);
        Texto.setRows(5);
        Texto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TextoKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(Texto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 891, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TextoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextoKeyPressed
        // TODO add your handling code here:
        /*if(evt.getKeyChar() == '\n')
        {
            Linea.setText("");
            int c = Texto.getLineCount();
            for(int x =  0; x <= c ; x++)
            {
                Linea.append(x+"\n");
            }
        }
        else if(evt.getKeyChar() == KeyEvent.VK_BACK_SPACE)
        {
            Linea.setText("");
            int c = Texto.getLineCount();
            for(int x =  0; x < c ; x++)
            {
                Linea.append(x+"\n");
            }
        }*/
    }//GEN-LAST:event_TextoKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Texto;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
