/* Generated By:JavaCC: Do not edit this line. ExpParserConstants.java */
package Exprs;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExpParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int mas = 1;
  /** RegularExpression Id. */
  int menos = 2;
  /** RegularExpression Id. */
  int por = 3;
  /** RegularExpression Id. */
  int div = 4;
  /** RegularExpression Id. */
  int mod = 5;
  /** RegularExpression Id. */
  int pot = 6;
  /** RegularExpression Id. */
  int igual = 7;
  /** RegularExpression Id. */
  int diferente = 8;
  /** RegularExpression Id. */
  int mayor = 9;
  /** RegularExpression Id. */
  int menor = 10;
  /** RegularExpression Id. */
  int mayorigual = 11;
  /** RegularExpression Id. */
  int menorigual = 12;
  /** RegularExpression Id. */
  int and = 13;
  /** RegularExpression Id. */
  int not = 14;
  /** RegularExpression Id. */
  int or = 15;
  /** RegularExpression Id. */
  int punto = 16;
  /** RegularExpression Id. */
  int dpunto = 17;
  /** RegularExpression Id. */
  int arroba = 18;
  /** RegularExpression Id. */
  int oPar = 19;
  /** RegularExpression Id. */
  int cPar = 20;
  /** RegularExpression Id. */
  int coma = 21;
  /** RegularExpression Id. */
  int f_cadena = 22;
  /** RegularExpression Id. */
  int f_subcad = 23;
  /** RegularExpression Id. */
  int f_poscad = 24;
  /** RegularExpression Id. */
  int f_booleano = 25;
  /** RegularExpression Id. */
  int f_entero = 26;
  /** RegularExpression Id. */
  int f_tam = 27;
  /** RegularExpression Id. */
  int f_pow = 28;
  /** RegularExpression Id. */
  int f_log = 29;
  /** RegularExpression Id. */
  int f_log10 = 30;
  /** RegularExpression Id. */
  int f_abs = 31;
  /** RegularExpression Id. */
  int f_sin = 32;
  /** RegularExpression Id. */
  int f_cos = 33;
  /** RegularExpression Id. */
  int f_tan = 34;
  /** RegularExpression Id. */
  int f_sqrt = 35;
  /** RegularExpression Id. */
  int f_pi = 36;
  /** RegularExpression Id. */
  int f_fecha = 37;
  /** RegularExpression Id. */
  int f_hora = 38;
  /** RegularExpression Id. */
  int f_fechahora = 39;
  /** RegularExpression Id. */
  int f_random = 40;
  /** RegularExpression Id. */
  int f_min = 41;
  /** RegularExpression Id. */
  int f_max = 42;
  /** RegularExpression Id. */
  int f_hoy = 43;
  /** RegularExpression Id. */
  int f_ahora = 44;
  /** RegularExpression Id. */
  int identificador = 50;
  /** RegularExpression Id. */
  int entero = 51;
  /** RegularExpression Id. */
  int decimal = 52;
  /** RegularExpression Id. */
  int str1 = 53;
  /** RegularExpression Id. */
  int str2 = 54;
  /** RegularExpression Id. */
  int verdadero = 55;
  /** RegularExpression Id. */
  int falso = 56;
  /** RegularExpression Id. */
  int fecha = 57;
  /** RegularExpression Id. */
  int hora = 58;
  /** RegularExpression Id. */
  int fechahora = 59;
  /** RegularExpression Id. */
  int err = 60;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"div\"",
    "\"mod\"",
    "\"^\"",
    "\"=\"",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"&&\"",
    "\"!\"",
    "\"||\"",
    "\".\"",
    "\"..\"",
    "\"@\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"cadena\"",
    "\"subcad\"",
    "\"poscad\"",
    "\"booleano\"",
    "\"entero\"",
    "\"tam\"",
    "\"pow\"",
    "\"log\"",
    "\"log10\"",
    "\"abs\"",
    "\"sin\"",
    "\"cos\"",
    "\"tan\"",
    "\"sqrt\"",
    "\"pi\"",
    "\"fecha\"",
    "\"hora\"",
    "\"fechahora\"",
    "\"random\"",
    "\"min\"",
    "\"max\"",
    "\"hoy\"",
    "\"ahora\"",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\t\"",
    "<identificador>",
    "<entero>",
    "<decimal>",
    "<str1>",
    "<str2>",
    "\"verdadero\"",
    "\"falso\"",
    "<fecha>",
    "<hora>",
    "<fechahora>",
    "<err>",
  };

}
