/* Generated By:JavaCC: Do not edit this line. ExpParserConstants.java */
package Exprs;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExpParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int mas = 1;
  /** RegularExpression Id. */
  int menos = 2;
  /** RegularExpression Id. */
  int por = 3;
  /** RegularExpression Id. */
  int div = 4;
  /** RegularExpression Id. */
  int mod = 5;
  /** RegularExpression Id. */
  int pot = 6;
  /** RegularExpression Id. */
  int igual = 7;
  /** RegularExpression Id. */
  int diferente = 8;
  /** RegularExpression Id. */
  int mayor = 9;
  /** RegularExpression Id. */
  int menor = 10;
  /** RegularExpression Id. */
  int mayorigual = 11;
  /** RegularExpression Id. */
  int menorigual = 12;
  /** RegularExpression Id. */
  int and = 13;
  /** RegularExpression Id. */
  int not = 14;
  /** RegularExpression Id. */
  int or = 15;
  /** RegularExpression Id. */
  int punto = 16;
  /** RegularExpression Id. */
  int dpunto = 17;
  /** RegularExpression Id. */
  int arroba = 18;
  /** RegularExpression Id. */
  int oPar = 19;
  /** RegularExpression Id. */
  int cPar = 20;
  /** RegularExpression Id. */
  int hoy = 21;
  /** RegularExpression Id. */
  int ahora = 22;
  /** RegularExpression Id. */
  int identificador = 23;
  /** RegularExpression Id. */
  int entero = 24;
  /** RegularExpression Id. */
  int decimal = 25;
  /** RegularExpression Id. */
  int str1 = 26;
  /** RegularExpression Id. */
  int str2 = 27;
  /** RegularExpression Id. */
  int verdadero = 28;
  /** RegularExpression Id. */
  int falso = 29;
  /** RegularExpression Id. */
  int fecha = 30;
  /** RegularExpression Id. */
  int hora = 31;
  /** RegularExpression Id. */
  int fechahora = 32;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"div\"",
    "\"mod\"",
    "\"^\"",
    "\"=\"",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"&&\"",
    "\"!\"",
    "\"||\"",
    "\".\"",
    "\"..\"",
    "\"@\"",
    "\"(\"",
    "\")\"",
    "\"hoy()\"",
    "\"ahora()\"",
    "<identificador>",
    "<entero>",
    "<decimal>",
    "<str1>",
    "<str2>",
    "\"verdadero\"",
    "\"falso\"",
    "<fecha>",
    "<hora>",
    "<fechahora>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"\\t\"",
  };

}
